// SPDX-License-Identifier: MIT
// Copyright 2026 Micah Makaiwi
// This source code is subject to the terms of the MIT license.
// If a copy of the license was not distributed with this file,
// you can obtain one at https://github.com/mmkiwi/AotDialogs/blob/main/LICENSE.md

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace MMKiwi.AotDialogs.WindowsCom;

[SupportedOSPlatform("windows6.0.6000")]
[SuppressMessage("ReSharper", "InconsistentNaming", Justification = "Matching windows API")]
public static class NativeStructs
{
    [NativeMarshalling(typeof(COMDLG_FILTERSPECMarshaller))]
    internal struct COMDLG_FILTERSPEC
    {
        [MarshalAs(UnmanagedType.LPWStr)] internal string? pszName;

        [MarshalAs(UnmanagedType.LPWStr)] internal string? pszSpec;

        [CustomMarshaller(typeof(COMDLG_FILTERSPEC), MarshalMode.Default, typeof(COMDLG_FILTERSPECMarshaller))]
        internal static class COMDLG_FILTERSPECMarshaller
        {
            public static unsafe COMDLG_FILTERSPECNative ConvertToUnmanaged(COMDLG_FILTERSPEC managed)
            {
                ushort* pszName = Utf16StringMarshaller.ConvertToUnmanaged(managed.pszName);
                ushort* pszSpec = Utf16StringMarshaller.ConvertToUnmanaged(managed.pszSpec);
                return new COMDLG_FILTERSPECNative { pszName = pszName, pszSpec = pszSpec, };
            }

            public static unsafe COMDLG_FILTERSPEC ConvertToManaged(COMDLG_FILTERSPECNative unmanaged)
            {
                string? pszName = Utf16StringMarshaller.ConvertToManaged(unmanaged.pszName);
                string? pszSpec = Utf16StringMarshaller.ConvertToManaged(unmanaged.pszSpec);
                return new COMDLG_FILTERSPEC { pszName = pszName, pszSpec = pszSpec, };
            }

            public static unsafe void Free(COMDLG_FILTERSPECNative unmanaged)
            {
                Utf16StringMarshaller.Free(unmanaged.pszName);
                Utf16StringMarshaller.Free(unmanaged.pszSpec);
            }
        }

        internal unsafe struct COMDLG_FILTERSPECNative
        {
            internal ushort* pszName;
            internal ushort* pszSpec;
        }
    }

    // Based off the code generated by CSWin32
    [DebuggerDisplay("{DebuggerDisplay,nq}")]
    [NativeMarshalling(typeof(HRESULTMarshaller))]
    [StructLayout(LayoutKind.Sequential)]
    internal readonly struct HRESULT : IEquatable<HRESULT>
    {
        internal readonly int Value;

        [CustomMarshaller(typeof(HRESULT), MarshalMode.Default, typeof(HRESULTMarshaller))]
        internal static class HRESULTMarshaller
        {
            public static int ConvertToUnmanaged(HRESULT managed)
            {
                return managed.Value;
            }

            public static HRESULT ConvertToManaged(int unmanaged)
            {
                return new HRESULT(unmanaged);
            }
        }

        internal HRESULT(int value) => this.Value = value;

        public static implicit operator int(HRESULT value) => value.Value;

        public static explicit operator HRESULT(int value) => new(value);

        public static bool operator ==(HRESULT left, HRESULT right) => left.Value == right.Value;

        public static bool operator !=(HRESULT left, HRESULT right) => !(left == right);

        public bool Equals(HRESULT other) => this.Value == other.Value;

        public override bool Equals(object? obj) => obj is HRESULT other && this.Equals(other);

        public override int GetHashCode() => this.Value.GetHashCode();


        public override string ToString() =>
            string.Format(System.Globalization.CultureInfo.InvariantCulture, "0x{0:X8}", this.Value);

        public static implicit operator uint(HRESULT value) => (uint)value.Value;

        public static explicit operator HRESULT(uint value) => new HRESULT(unchecked((int)value));

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        internal bool Succeeded => this.Value >= 0;

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        internal bool Failed => this.Value < 0;

        internal HRESULT ThrowOnFailure(IntPtr errorInfo = 0)
        {
            Marshal.ThrowExceptionForHR(this.Value, errorInfo);
            return this;
        }

        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        private string DebuggerDisplay
        {
            get
            {
                return string.Format("{0} {1}", ToString(),
                    new System.ComponentModel.Win32Exception((int)this.Value).Message);
            }
        }

        internal string ToString(string format, IFormatProvider formatProvider) =>
            ((uint)this.Value).ToString(format, formatProvider);
    }

    // Not used, removing from assembly. All methods take a pointer to this struct

#if FALSE
    internal struct PROPERTYKEY
    {
        internal Guid FmtId;
        internal uint PropertyId;
    }
#endif
}